### ISSUE TITLE
[FE] Feat: 기본 화면 구현(전체 레이아웃)

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#15]
## To-do List

- [ ] 전체 레이아웃
- [ ] header 및 footer (필요한 경우)

## Deadline

230723 12:00

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
