### ISSUE TITLE
[FE] Design: 활동 계획 달력 내비게이션 구현(AJAX)

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#29]
## To-do List

- [ ] JSP-Spring Boot AJAX 통신 응답 데이터 형식 해결
- [ ] 달력 내비게이션 시 계산 결과 고정

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
