### ISSUE TITLE
[FE] Design: 활동 계획 달력에 '활동일' 및 '오늘' 별도 표시 구현

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#30]
## To-do List

- [ ] 활동 계획 달력 사이즈 조정 
- [ ] 활동 계획 달력에 '활동일' 표시(dot, 글씨 색깔 등)
- [ ] 활동 계획 달력에 '오늘' 음영 표시

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
