### ISSUE TITLE
[B/FE] Feat: 나의 일정 상세 보기 구현 

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#34]
## To-do List

- [ ] 나의 일정 상세 보기 JSP 작성
- [ ] 나의 일정 상세 보기 controller, service, repository 작성
- [ ] 필요한 통계 자료 처리

## Deadline

230728 3:00

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
