### ISSUE TITLE
[B/FE] Feat: 회원 정보 수정 및 탈퇴 구현

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#41]
## To-do List

- [ ] 프로필 사진 추가 구현
- [ ] 
- [ ] 
- [ ] 

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [ ] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [ ] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
