### ISSUE TITLE
[BE] Feat: 매퍼(Mapper)를 이용한 DTO-Entity 클래스 매핑

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#44]
## To-do List

- [x] MapStruct 리서치
- [x] MapStruct 사용 세팅
- [x] MapStruct 적용
- [ ] 테스트

## Deadline

230728 3:00

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
