### ISSUE TITLE
[B/FE] Feat: 메인페이지 구현

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#51]
## To-do List

- [ ] 메인페이지 View 구현
- [ ] 메임페이지 Controller, Service, Repsitory 구현
- [ ] 테스트 

## Deadline

230730 22:00

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
