### ISSUE TITLE
[FE] Design: 웹사이트 전체 디자인 

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#57]
## To-do List

- [ ] 웹사이트 전체 폰트 적용
- [ ] 웹사이트 전체 컬러 통일
- [ ] 웹사이트 전체 레이아웃 마무리
- [ ] 웹사이트 전체 버튼 및 이모지 활용 통일

## Deadline

230806

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
