### ISSUE TITLE
[BE] Feat: 전체 Entity 설계 및 구현

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#6]
## To-do List

- [x] 도메인별 Entity 작성

## Deadline

230719 / 23:59

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
