### ISSUE TITLE
[BE] Feat: Cloud Computing 활용 배포

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#68]
## To-do List

- [ ] 클라우드 컴퓨팅 계정 세팅
- [ ] 서버 컴퓨터 세팅
- [ ] DBMS 세팅
- [ ] 서버 컴퓨터에 프로젝트 올리기

## Deadline

230806 23:59

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
