### ISSUE TITLE
[BE] Feat: CI/CD 구축

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#69]
## To-do List

- [ ] GitHub Actions 활용 빌드 자동화
- [ ] AWS CodeDeploy 활용 배포 자동화

## Deadline

230806 23:59

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
