### ISSUE TITLE
[B/FE] Feat: 활동 통계 기획 및 구현

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#71]
## To-do List

- [ ] 활동 통계 내용 기획
- [ ] 활동 통계 구현을 위한 Service, Repository 구현
- [ ] Controller 및 View 구현

## Deadline

230804 23:59

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
