### ISSUE TITLE
[BE] Fix: 계획 저장 및 로그인 흐름 버그 수정 

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#72]
## To-do List

- [x] 비회원의 측정 불가능한 일 계획 계산 결과가 저장 안 되는 현상 수정
- [ ] 로그인 회원이 특정 경우에 메인페이지에서 활동 목록 볼 수 없는 현상 수정
- [ ] 
- [ ] 

## Deadline

230805 2:00

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
