### ISSUE TITLE
[B/FE] Fix: 전체적 UI 및 view 내용 보완

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#79]
## To-do List

- [x] 계산기 선택 input 만들기
- [x] 메인페이지 통계 내용 보완
- [ ] 계산 버그 수정
- [ ] 

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
