### ISSUE TITLE
[BE] Feat: Error Response, Exception 구현

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#8]
## To-do List

- [ ] Error Response 구현 
- [ ] Exception 구현
- [ ] 예외/오류 발생 시 redirect 페이지 구현

## Deadline

230719 / 23:59

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
