### ISSUE TITLE
[BE] Fix: 계산기 전반적인 로직 검토 및 이상 케이스 수정

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#93]
## To-do List

- [ ] 계산기 로직 전반적 검토
- [ ] 이상 케이스 리뷰 및 로직 수정 

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
