### ISSUE TITLE
[BE] Fix: 게시판 글 수정 페이지 로딩 시 500 에러 수정

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#97]
## To-do List

- [ ] could not initialize proxy 에러 해결
- [ ] 위 에러에 대한 근본적인 해결 방법 강구 및 전체 적용 

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
