### ISSUE TITLE
[FE] Design: font 사이즈 변경/조정

### ISSUE THREAD

**Issue by greenkey20** [greenkey20/knou-key-project#98]
## To-do List

- [ ] 반응형 웹형 폰트 사이즈 설정
- [ ] 모바일 브라우저에서 글씨 너무 작게 보이는 문제 해결

## Issue Checklist
아래 체크리스트를 확인해주세요.
- [x] Issue Title을 다음 예시와 같이 작성했습니다. (e.g. [BE] Feat: 회원가입 기능 구현 )
- [x] 우측의 Assignees, Labels, Projects, Milestone을 적절하게 선택했습니다.
